// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activities.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const listActivitiesByEntity = `-- name: ListActivitiesByEntity :many

SELECT id, entity_type, entity_id, actor_type, actor_id, event_type,
       source_system, payload, created_at
FROM activities
WHERE entity_type = $1::text
  AND entity_id   = $2::uuid
ORDER BY created_at DESC, id DESC
LIMIT $3::int
`

type ListActivitiesByEntityParams struct {
	EntityType string    `json:"entity_type"`
	EntityID   uuid.UUID `json:"entity_id"`
	PageLimit  int32     `json:"page_limit"`
}

// activities.sql — workspace-scoped activity timeline queries.
//
// All queries run with search_path = workspace_<uuid>; table names are
// unqualified. The REST surface is read-only — writes happen inside
// the same transaction as the entity mutation via the raw helper in
// apps/api/internal/crm/activity.go (fail-closed: a failed activity
// insert rolls back the mutation, mirroring ADR-009 §7.2).
func (q *Queries) ListActivitiesByEntity(ctx context.Context, arg ListActivitiesByEntityParams) ([]Activity, error) {
	rows, err := q.db.Query(ctx, listActivitiesByEntity, arg.EntityType, arg.EntityID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Activity{}
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.EntityID,
			&i.ActorType,
			&i.ActorID,
			&i.EventType,
			&i.SourceSystem,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
