// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: companies.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countCompanies = `-- name: CountCompanies :one
SELECT count(*) FROM companies
`

func (q *Queries) CountCompanies(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCompanies)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCompany = `-- name: CreateCompany :one
INSERT INTO companies (name, domain, industry, size, owner_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, domain, industry, size, owner_id, created_at, updated_at
`

type CreateCompanyParams struct {
	Name     string        `json:"name"`
	Domain   pgtype.Text   `json:"domain"`
	Industry pgtype.Text   `json:"industry"`
	Size     pgtype.Text   `json:"size"`
	OwnerID  uuid.NullUUID `json:"owner_id"`
}

func (q *Queries) CreateCompany(ctx context.Context, arg CreateCompanyParams) (Company, error) {
	row := q.db.QueryRow(ctx, createCompany,
		arg.Name,
		arg.Domain,
		arg.Industry,
		arg.Size,
		arg.OwnerID,
	)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.Industry,
		&i.Size,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCompany = `-- name: DeleteCompany :exec
DELETE FROM companies WHERE id = $1
`

func (q *Queries) DeleteCompany(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCompany, id)
	return err
}

const getCompany = `-- name: GetCompany :one
SELECT id, name, domain, industry, size, owner_id, created_at, updated_at
FROM companies
WHERE id = $1
`

func (q *Queries) GetCompany(ctx context.Context, id uuid.UUID) (Company, error) {
	row := q.db.QueryRow(ctx, getCompany, id)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.Industry,
		&i.Size,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCompanies = `-- name: ListCompanies :many

SELECT id, name, domain, industry, size, owner_id, created_at, updated_at
FROM companies
WHERE
  $1::timestamptz IS NULL
  OR created_at < $1::timestamptz
  OR (created_at = $1::timestamptz AND id < $2::uuid)
ORDER BY created_at DESC, id DESC
LIMIT $3::int
`

type ListCompaniesParams struct {
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        uuid.UUID          `json:"cursor_id"`
	PageLimit       int32              `json:"page_limit"`
}

// companies.sql — CRUD queries for the workspace-scoped companies table.
//
// Queries run with search_path = workspace_<uuid>, so table names are unqualified.
// Cursor-based pagination: pass NULL cursor_created_at for the first page.
func (q *Queries) ListCompanies(ctx context.Context, arg ListCompaniesParams) ([]Company, error) {
	rows, err := q.db.Query(ctx, listCompanies, arg.CursorCreatedAt, arg.CursorID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Company{}
	for rows.Next() {
		var i Company
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Domain,
			&i.Industry,
			&i.Size,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCompany = `-- name: UpdateCompany :one
UPDATE companies
SET name       = COALESCE(NULLIF($1::text, ''), name),
    domain     = $2,
    industry   = $3,
    size       = $4,
    owner_id   = $5,
    updated_at = now()
WHERE id = $6
RETURNING id, name, domain, industry, size, owner_id, created_at, updated_at
`

type UpdateCompanyParams struct {
	Name     string        `json:"name"`
	Domain   pgtype.Text   `json:"domain"`
	Industry pgtype.Text   `json:"industry"`
	Size     pgtype.Text   `json:"size"`
	OwnerID  uuid.NullUUID `json:"owner_id"`
	ID       uuid.UUID     `json:"id"`
}

func (q *Queries) UpdateCompany(ctx context.Context, arg UpdateCompanyParams) (Company, error) {
	row := q.db.QueryRow(ctx, updateCompany,
		arg.Name,
		arg.Domain,
		arg.Industry,
		arg.Size,
		arg.OwnerID,
		arg.ID,
	)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.Industry,
		&i.Size,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
