// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contacts.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countContacts = `-- name: CountContacts :one
SELECT count(*) FROM contacts
`

func (q *Queries) CountContacts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countContacts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createContact = `-- name: CreateContact :one
INSERT INTO contacts (first_name, last_name, email, phone, company_id, owner_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, first_name, last_name, email, phone, company_id, owner_id, created_at, updated_at
`

type CreateContactParams struct {
	FirstName string        `json:"first_name"`
	LastName  string        `json:"last_name"`
	Email     pgtype.Text   `json:"email"`
	Phone     pgtype.Text   `json:"phone"`
	CompanyID uuid.NullUUID `json:"company_id"`
	OwnerID   uuid.NullUUID `json:"owner_id"`
}

func (q *Queries) CreateContact(ctx context.Context, arg CreateContactParams) (Contact, error) {
	row := q.db.QueryRow(ctx, createContact,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Phone,
		arg.CompanyID,
		arg.OwnerID,
	)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.CompanyID,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteContact = `-- name: DeleteContact :exec
DELETE FROM contacts WHERE id = $1
`

func (q *Queries) DeleteContact(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteContact, id)
	return err
}

const getContact = `-- name: GetContact :one
SELECT id, first_name, last_name, email, phone, company_id, owner_id, created_at, updated_at
FROM contacts
WHERE id = $1
`

func (q *Queries) GetContact(ctx context.Context, id uuid.UUID) (Contact, error) {
	row := q.db.QueryRow(ctx, getContact, id)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.CompanyID,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listContacts = `-- name: ListContacts :many

SELECT id, first_name, last_name, email, phone, company_id, owner_id, created_at, updated_at
FROM contacts
WHERE
  $1::timestamptz IS NULL
  OR created_at < $1::timestamptz
  OR (created_at = $1::timestamptz AND id < $2::uuid)
ORDER BY created_at DESC, id DESC
LIMIT $3::int
`

type ListContactsParams struct {
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        uuid.UUID          `json:"cursor_id"`
	PageLimit       int32              `json:"page_limit"`
}

// contacts.sql — CRUD queries for the workspace-scoped contacts table.
//
// Queries run with search_path = workspace_<uuid>, so table names are unqualified.
// Cursor-based pagination: pass NULL cursor_created_at for the first page.
func (q *Queries) ListContacts(ctx context.Context, arg ListContactsParams) ([]Contact, error) {
	rows, err := q.db.Query(ctx, listContacts, arg.CursorCreatedAt, arg.CursorID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Contact{}
	for rows.Next() {
		var i Contact
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Phone,
			&i.CompanyID,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContact = `-- name: UpdateContact :one
UPDATE contacts
SET first_name = COALESCE(NULLIF($1::text, ''), first_name),
    last_name  = COALESCE(NULLIF($2::text, ''), last_name),
    email      = $3,
    phone      = $4,
    company_id = $5,
    owner_id   = $6,
    updated_at = now()
WHERE id = $7
RETURNING id, first_name, last_name, email, phone, company_id, owner_id, created_at, updated_at
`

type UpdateContactParams struct {
	FirstName string        `json:"first_name"`
	LastName  string        `json:"last_name"`
	Email     pgtype.Text   `json:"email"`
	Phone     pgtype.Text   `json:"phone"`
	CompanyID uuid.NullUUID `json:"company_id"`
	OwnerID   uuid.NullUUID `json:"owner_id"`
	ID        uuid.UUID     `json:"id"`
}

func (q *Queries) UpdateContact(ctx context.Context, arg UpdateContactParams) (Contact, error) {
	row := q.db.QueryRow(ctx, updateContact,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Phone,
		arg.CompanyID,
		arg.OwnerID,
		arg.ID,
	)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.CompanyID,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
