// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deals.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countDeals = `-- name: CountDeals :one
SELECT count(*) FROM deals
`

func (q *Queries) CountDeals(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countDeals)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDeal = `-- name: CreateDeal :one
INSERT INTO deals (title, amount, currency, stage_id, contact_id, company_id, owner_id, expected_close_date)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, title, amount, currency, stage_id, contact_id, company_id,
          owner_id, expected_close_date, closed_at, created_at, updated_at
`

type CreateDealParams struct {
	Title             string         `json:"title"`
	Amount            pgtype.Numeric `json:"amount"`
	Currency          pgtype.Text    `json:"currency"`
	StageID           uuid.NullUUID  `json:"stage_id"`
	ContactID         uuid.NullUUID  `json:"contact_id"`
	CompanyID         uuid.NullUUID  `json:"company_id"`
	OwnerID           uuid.NullUUID  `json:"owner_id"`
	ExpectedCloseDate pgtype.Date    `json:"expected_close_date"`
}

func (q *Queries) CreateDeal(ctx context.Context, arg CreateDealParams) (Deal, error) {
	row := q.db.QueryRow(ctx, createDeal,
		arg.Title,
		arg.Amount,
		arg.Currency,
		arg.StageID,
		arg.ContactID,
		arg.CompanyID,
		arg.OwnerID,
		arg.ExpectedCloseDate,
	)
	var i Deal
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Amount,
		&i.Currency,
		&i.StageID,
		&i.ContactID,
		&i.CompanyID,
		&i.OwnerID,
		&i.ExpectedCloseDate,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDeal = `-- name: DeleteDeal :exec
DELETE FROM deals WHERE id = $1
`

func (q *Queries) DeleteDeal(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDeal, id)
	return err
}

const getDeal = `-- name: GetDeal :one
SELECT id, title, amount, currency, stage_id, contact_id, company_id,
       owner_id, expected_close_date, closed_at, created_at, updated_at
FROM deals
WHERE id = $1
`

func (q *Queries) GetDeal(ctx context.Context, id uuid.UUID) (Deal, error) {
	row := q.db.QueryRow(ctx, getDeal, id)
	var i Deal
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Amount,
		&i.Currency,
		&i.StageID,
		&i.ContactID,
		&i.CompanyID,
		&i.OwnerID,
		&i.ExpectedCloseDate,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDeals = `-- name: ListDeals :many

SELECT id, title, amount, currency, stage_id, contact_id, company_id,
       owner_id, expected_close_date, closed_at, created_at, updated_at
FROM deals
WHERE
  $1::timestamptz IS NULL
  OR created_at < $1::timestamptz
  OR (created_at = $1::timestamptz AND id < $2::uuid)
ORDER BY created_at DESC, id DESC
LIMIT $3::int
`

type ListDealsParams struct {
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        uuid.UUID          `json:"cursor_id"`
	PageLimit       int32              `json:"page_limit"`
}

// deals.sql — CRUD queries for the workspace-scoped deals table.
//
// Queries run with search_path = workspace_<uuid>, so table names are unqualified.
// Cursor-based pagination: pass NULL cursor_created_at for the first page.
func (q *Queries) ListDeals(ctx context.Context, arg ListDealsParams) ([]Deal, error) {
	rows, err := q.db.Query(ctx, listDeals, arg.CursorCreatedAt, arg.CursorID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deal{}
	for rows.Next() {
		var i Deal
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Amount,
			&i.Currency,
			&i.StageID,
			&i.ContactID,
			&i.CompanyID,
			&i.OwnerID,
			&i.ExpectedCloseDate,
			&i.ClosedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDealsByStage = `-- name: ListDealsByStage :many
SELECT id, title, amount, currency, stage_id, contact_id, company_id,
       owner_id, expected_close_date, closed_at, created_at, updated_at
FROM deals
WHERE stage_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListDealsByStage(ctx context.Context, stageID uuid.NullUUID) ([]Deal, error) {
	rows, err := q.db.Query(ctx, listDealsByStage, stageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deal{}
	for rows.Next() {
		var i Deal
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Amount,
			&i.Currency,
			&i.StageID,
			&i.ContactID,
			&i.CompanyID,
			&i.OwnerID,
			&i.ExpectedCloseDate,
			&i.ClosedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeal = `-- name: UpdateDeal :one
UPDATE deals
SET title               = COALESCE(NULLIF($1::text, ''), title),
    amount              = $2,
    currency            = $3,
    stage_id            = $4,
    contact_id          = $5,
    company_id          = $6,
    owner_id            = $7,
    expected_close_date = $8,
    updated_at          = now()
WHERE id = $9
RETURNING id, title, amount, currency, stage_id, contact_id, company_id,
          owner_id, expected_close_date, closed_at, created_at, updated_at
`

type UpdateDealParams struct {
	Title             string         `json:"title"`
	Amount            pgtype.Numeric `json:"amount"`
	Currency          pgtype.Text    `json:"currency"`
	StageID           uuid.NullUUID  `json:"stage_id"`
	ContactID         uuid.NullUUID  `json:"contact_id"`
	CompanyID         uuid.NullUUID  `json:"company_id"`
	OwnerID           uuid.NullUUID  `json:"owner_id"`
	ExpectedCloseDate pgtype.Date    `json:"expected_close_date"`
	ID                uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateDeal(ctx context.Context, arg UpdateDealParams) (Deal, error) {
	row := q.db.QueryRow(ctx, updateDeal,
		arg.Title,
		arg.Amount,
		arg.Currency,
		arg.StageID,
		arg.ContactID,
		arg.CompanyID,
		arg.OwnerID,
		arg.ExpectedCloseDate,
		arg.ID,
	)
	var i Deal
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Amount,
		&i.Currency,
		&i.StageID,
		&i.ContactID,
		&i.CompanyID,
		&i.OwnerID,
		&i.ExpectedCloseDate,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDealStage = `-- name: UpdateDealStage :one
UPDATE deals
SET stage_id   = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, title, amount, currency, stage_id, contact_id, company_id,
          owner_id, expected_close_date, closed_at, created_at, updated_at
`

type UpdateDealStageParams struct {
	ID      uuid.UUID     `json:"id"`
	StageID uuid.NullUUID `json:"stage_id"`
}

func (q *Queries) UpdateDealStage(ctx context.Context, arg UpdateDealStageParams) (Deal, error) {
	row := q.db.QueryRow(ctx, updateDealStage, arg.ID, arg.StageID)
	var i Deal
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Amount,
		&i.Currency,
		&i.StageID,
		&i.ContactID,
		&i.CompanyID,
		&i.OwnerID,
		&i.ExpectedCloseDate,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
