// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type CoreAuditLog struct {
	ID          int64              `json:"id"`
	OccurredAt  pgtype.Timestamptz `json:"occurred_at"`
	Event       string             `json:"event"`
	WorkspaceID uuid.NullUUID      `json:"workspace_id"`
	ActorType   pgtype.Text        `json:"actor_type"`
	ActorUserID uuid.NullUUID      `json:"actor_user_id"`
	ActorIp     *netip.Addr        `json:"actor_ip"`
	RequestID   uuid.NullUUID      `json:"request_id"`
	Payload     []byte             `json:"payload"`
}

type CoreReservedSlug struct {
	Slug      string             `json:"slug"`
	Reason    string             `json:"reason"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type CoreUser struct {
	ID          uuid.UUID          `json:"id"`
	Issuer      string             `json:"issuer"`
	Subject     string             `json:"subject"`
	Email       pgtype.Text        `json:"email"`
	DisplayName pgtype.Text        `json:"display_name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
}

type CoreWorkspace struct {
	ID                          uuid.UUID          `json:"id"`
	Slug                        string             `json:"slug"`
	RoleName                    string             `json:"role_name"`
	CreatedAt                   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                   pgtype.Timestamptz `json:"updated_at"`
	AdminEmail                  string             `json:"admin_email"`
	CreatorEmail                string             `json:"creator_email"`
	ProvisioningFeaturesApplied []byte             `json:"provisioning_features_applied"`
	TombstonedAt                pgtype.Timestamptz `json:"tombstoned_at"`
}

type CoreWorkspaceMember struct {
	WorkspaceID uuid.UUID          `json:"workspace_id"`
	UserID      uuid.UUID          `json:"user_id"`
	Role        string             `json:"role"`
	InvitedAt   pgtype.Timestamptz `json:"invited_at"`
	JoinedAt    pgtype.Timestamptz `json:"joined_at"`
}
