// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql/driver"
	"fmt"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type EnrollmentState string

const (
	EnrollmentStateEnrolled      EnrollmentState = "enrolled"
	EnrollmentStateStepSent      EnrollmentState = "step_sent"
	EnrollmentStateWaitingReply  EnrollmentState = "waiting_reply"
	EnrollmentStateReplyReceived EnrollmentState = "reply_received"
	EnrollmentStateOooDetected   EnrollmentState = "ooo_detected"
	EnrollmentStateFailed        EnrollmentState = "failed"
	EnrollmentStateBounced       EnrollmentState = "bounced"
	EnrollmentStateUnsubscribed  EnrollmentState = "unsubscribed"
	EnrollmentStateSuppressed    EnrollmentState = "suppressed"
	EnrollmentStateCompleted     EnrollmentState = "completed"
)

func (e *EnrollmentState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EnrollmentState(s)
	case string:
		*e = EnrollmentState(s)
	default:
		return fmt.Errorf("unsupported scan type for EnrollmentState: %T", src)
	}
	return nil
}

type NullEnrollmentState struct {
	EnrollmentState EnrollmentState `json:"enrollment_state"`
	Valid           bool            `json:"valid"` // Valid is true if EnrollmentState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEnrollmentState) Scan(value interface{}) error {
	if value == nil {
		ns.EnrollmentState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EnrollmentState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEnrollmentState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EnrollmentState), nil
}

type StepSendState string

const (
	StepSendStatePending    StepSendState = "pending"
	StepSendStateSent       StepSendState = "sent"
	StepSendStateDelivered  StepSendState = "delivered"
	StepSendStateBounced    StepSendState = "bounced"
	StepSendStateCancelled  StepSendState = "cancelled"
	StepSendStateSuperseded StepSendState = "superseded"
)

func (e *StepSendState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StepSendState(s)
	case string:
		*e = StepSendState(s)
	default:
		return fmt.Errorf("unsupported scan type for StepSendState: %T", src)
	}
	return nil
}

type NullStepSendState struct {
	StepSendState StepSendState `json:"step_send_state"`
	Valid         bool          `json:"valid"` // Valid is true if StepSendState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStepSendState) Scan(value interface{}) error {
	if value == nil {
		ns.StepSendState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StepSendState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStepSendState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StepSendState), nil
}

type Activity struct {
	ID           uuid.UUID          `json:"id"`
	EntityType   string             `json:"entity_type"`
	EntityID     uuid.UUID          `json:"entity_id"`
	ActorType    pgtype.Text        `json:"actor_type"`
	ActorID      uuid.NullUUID      `json:"actor_id"`
	EventType    string             `json:"event_type"`
	SourceSystem pgtype.Text        `json:"source_system"`
	Payload      []byte             `json:"payload"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Company struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Domain    pgtype.Text        `json:"domain"`
	Industry  pgtype.Text        `json:"industry"`
	Size      pgtype.Text        `json:"size"`
	OwnerID   uuid.NullUUID      `json:"owner_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Contact struct {
	ID        uuid.UUID          `json:"id"`
	FirstName string             `json:"first_name"`
	LastName  string             `json:"last_name"`
	Email     pgtype.Text        `json:"email"`
	Phone     pgtype.Text        `json:"phone"`
	CompanyID uuid.NullUUID      `json:"company_id"`
	OwnerID   uuid.NullUUID      `json:"owner_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type CoreAuditLog struct {
	ID          int64              `json:"id"`
	OccurredAt  pgtype.Timestamptz `json:"occurred_at"`
	Event       string             `json:"event"`
	WorkspaceID uuid.NullUUID      `json:"workspace_id"`
	ActorType   string             `json:"actor_type"`
	ActorUserID uuid.NullUUID      `json:"actor_user_id"`
	ActorIp     *netip.Addr        `json:"actor_ip"`
	RequestID   uuid.NullUUID      `json:"request_id"`
	Payload     []byte             `json:"payload"`
}

type CoreIdempotencyKey struct {
	Key            string             `json:"key"`
	WorkspaceID    uuid.UUID          `json:"workspace_id"`
	Method         string             `json:"method"`
	Path           string             `json:"path"`
	ResponseStatus int32              `json:"response_status"`
	ResponseBody   []byte             `json:"response_body"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
}

type CoreIntegratorGrant struct {
	WorkspaceID uuid.UUID          `json:"workspace_id"`
	Email       string             `json:"email"`
	GrantedBy   string             `json:"granted_by"`
	GrantedAt   pgtype.Timestamptz `json:"granted_at"`
}

type CoreReservedSlug struct {
	Slug      string             `json:"slug"`
	Reason    string             `json:"reason"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type CoreServiceToken struct {
	ID          uuid.UUID          `json:"id"`
	WorkspaceID uuid.UUID          `json:"workspace_id"`
	Name        string             `json:"name"`
	TokenHash   string             `json:"token_hash"`
	ActorType   string             `json:"actor_type"`
	Scopes      []byte             `json:"scopes"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt  pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

// Per-session revocation entries. Checked via in-memory bloom filter; DB hit only on bloom-positive. Rows auto-expire and are cleaned by a periodic job.
type CoreSessionRevocation struct {
	Jti       uuid.UUID          `json:"jti"`
	UserID    uuid.UUID          `json:"user_id"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type CoreUser struct {
	ID          uuid.UUID          `json:"id"`
	Issuer      string             `json:"issuer"`
	Subject     string             `json:"subject"`
	Email       pgtype.Text        `json:"email"`
	DisplayName pgtype.Text        `json:"display_name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
}

// User-level revocation: all sessions issued before revoked_at are invalid. Used for account compromise scenario (revoke-all).
type CoreUserRevocation struct {
	UserID    uuid.UUID          `json:"user_id"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

type CoreWorkspace struct {
	ID                          uuid.UUID          `json:"id"`
	Slug                        string             `json:"slug"`
	RoleName                    string             `json:"role_name"`
	CreatedAt                   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                   pgtype.Timestamptz `json:"updated_at"`
	AdminEmail                  string             `json:"admin_email"`
	CreatorEmail                string             `json:"creator_email"`
	ProvisioningFeaturesApplied []byte             `json:"provisioning_features_applied"`
	TombstonedAt                pgtype.Timestamptz `json:"tombstoned_at"`
}

type CoreWorkspaceMember struct {
	WorkspaceID uuid.UUID          `json:"workspace_id"`
	UserID      uuid.UUID          `json:"user_id"`
	Role        string             `json:"role"`
	InvitedAt   pgtype.Timestamptz `json:"invited_at"`
	JoinedAt    pgtype.Timestamptz `json:"joined_at"`
}

type Deal struct {
	ID                uuid.UUID          `json:"id"`
	Title             string             `json:"title"`
	Amount            pgtype.Numeric     `json:"amount"`
	Currency          pgtype.Text        `json:"currency"`
	StageID           uuid.NullUUID      `json:"stage_id"`
	ContactID         uuid.NullUUID      `json:"contact_id"`
	CompanyID         uuid.NullUUID      `json:"company_id"`
	OwnerID           uuid.NullUUID      `json:"owner_id"`
	ExpectedCloseDate pgtype.Date        `json:"expected_close_date"`
	ClosedAt          pgtype.Timestamptz `json:"closed_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type Enrollment struct {
	ID               uuid.UUID          `json:"id"`
	SequenceID       uuid.UUID          `json:"sequence_id"`
	ContactID        uuid.UUID          `json:"contact_id"`
	State            EnrollmentState    `json:"state"`
	CurrentStepIndex int16              `json:"current_step_index"`
	EnrolledAt       pgtype.Timestamptz `json:"enrolled_at"`
	NextActionAt     pgtype.Timestamptz `json:"next_action_at"`
	LastTransitionAt pgtype.Timestamptz `json:"last_transition_at"`
	ReplyMessageID   pgtype.Text        `json:"reply_message_id"`
	OooReturnsAt     pgtype.Timestamptz `json:"ooo_returns_at"`
	CreatedByUserID  uuid.NullUUID      `json:"created_by_user_id"`
	WorkspaceID      uuid.UUID          `json:"workspace_id"`
}

type EnrollmentStep struct {
	ID             uuid.UUID          `json:"id"`
	EnrollmentID   uuid.UUID          `json:"enrollment_id"`
	StepIndex      int16              `json:"step_index"`
	State          StepSendState      `json:"state"`
	BrevoMessageID pgtype.Text        `json:"brevo_message_id"`
	RfcMessageID   pgtype.Text        `json:"rfc_message_id"`
	ScheduledFor   pgtype.Timestamptz `json:"scheduled_for"`
	SentAt         pgtype.Timestamptz `json:"sent_at"`
	DeliveredAt    pgtype.Timestamptz `json:"delivered_at"`
	BouncedAt      pgtype.Timestamptz `json:"bounced_at"`
	BounceType     pgtype.Text        `json:"bounce_type"`
	IdempotencyKey string             `json:"idempotency_key"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Note struct {
	ID         uuid.UUID          `json:"id"`
	EntityType string             `json:"entity_type"`
	EntityID   uuid.UUID          `json:"entity_id"`
	Body       string             `json:"body"`
	AuthorID   uuid.UUID          `json:"author_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type PipelineStage struct {
	ID         uuid.UUID          `json:"id"`
	Name       string             `json:"name"`
	OrderIndex int32              `json:"order_index"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Task struct {
	ID          uuid.UUID          `json:"id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	EntityType  pgtype.Text        `json:"entity_type"`
	EntityID    uuid.NullUUID      `json:"entity_id"`
	AssigneeID  uuid.NullUUID      `json:"assignee_id"`
	DueDate     pgtype.Date        `json:"due_date"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
