// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Activity struct {
	ID           uuid.UUID          `json:"id"`
	EntityType   string             `json:"entity_type"`
	EntityID     uuid.UUID          `json:"entity_id"`
	ActorType    pgtype.Text        `json:"actor_type"`
	ActorID      uuid.NullUUID      `json:"actor_id"`
	EventType    string             `json:"event_type"`
	SourceSystem pgtype.Text        `json:"source_system"`
	Payload      []byte             `json:"payload"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Company struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Domain    pgtype.Text        `json:"domain"`
	Industry  pgtype.Text        `json:"industry"`
	Size      pgtype.Text        `json:"size"`
	OwnerID   uuid.NullUUID      `json:"owner_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Contact struct {
	ID        uuid.UUID          `json:"id"`
	FirstName string             `json:"first_name"`
	LastName  string             `json:"last_name"`
	Email     pgtype.Text        `json:"email"`
	Phone     pgtype.Text        `json:"phone"`
	CompanyID uuid.NullUUID      `json:"company_id"`
	OwnerID   uuid.NullUUID      `json:"owner_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type CoreAuditLog struct {
	ID          int64              `json:"id"`
	OccurredAt  pgtype.Timestamptz `json:"occurred_at"`
	Event       string             `json:"event"`
	WorkspaceID uuid.NullUUID      `json:"workspace_id"`
	ActorType   pgtype.Text        `json:"actor_type"`
	ActorUserID uuid.NullUUID      `json:"actor_user_id"`
	ActorIp     *netip.Addr        `json:"actor_ip"`
	RequestID   uuid.NullUUID      `json:"request_id"`
	Payload     []byte             `json:"payload"`
}

type CoreIdempotencyKey struct {
	Key            string             `json:"key"`
	WorkspaceID    uuid.UUID          `json:"workspace_id"`
	Method         string             `json:"method"`
	Path           string             `json:"path"`
	ResponseStatus int32              `json:"response_status"`
	ResponseBody   []byte             `json:"response_body"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
}

type CoreReservedSlug struct {
	Slug      string             `json:"slug"`
	Reason    string             `json:"reason"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// Per-session revocation entries. Checked via in-memory bloom filter; DB hit only on bloom-positive. Rows auto-expire and are cleaned by a periodic job.
type CoreSessionRevocation struct {
	Jti       uuid.UUID          `json:"jti"`
	UserID    uuid.UUID          `json:"user_id"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type CoreUser struct {
	ID          uuid.UUID          `json:"id"`
	Issuer      string             `json:"issuer"`
	Subject     string             `json:"subject"`
	Email       pgtype.Text        `json:"email"`
	DisplayName pgtype.Text        `json:"display_name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
}

// User-level revocation: all sessions issued before revoked_at are invalid. Used for account compromise scenario (revoke-all).
type CoreUserRevocation struct {
	UserID    uuid.UUID          `json:"user_id"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

type CoreWorkspace struct {
	ID                          uuid.UUID          `json:"id"`
	Slug                        string             `json:"slug"`
	RoleName                    string             `json:"role_name"`
	CreatedAt                   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                   pgtype.Timestamptz `json:"updated_at"`
	AdminEmail                  string             `json:"admin_email"`
	CreatorEmail                string             `json:"creator_email"`
	ProvisioningFeaturesApplied []byte             `json:"provisioning_features_applied"`
	TombstonedAt                pgtype.Timestamptz `json:"tombstoned_at"`
}

type CoreWorkspaceMember struct {
	WorkspaceID uuid.UUID          `json:"workspace_id"`
	UserID      uuid.UUID          `json:"user_id"`
	Role        string             `json:"role"`
	InvitedAt   pgtype.Timestamptz `json:"invited_at"`
	JoinedAt    pgtype.Timestamptz `json:"joined_at"`
}

type Deal struct {
	ID                uuid.UUID          `json:"id"`
	Title             string             `json:"title"`
	Amount            pgtype.Numeric     `json:"amount"`
	Currency          pgtype.Text        `json:"currency"`
	StageID           uuid.NullUUID      `json:"stage_id"`
	ContactID         uuid.NullUUID      `json:"contact_id"`
	CompanyID         uuid.NullUUID      `json:"company_id"`
	OwnerID           uuid.NullUUID      `json:"owner_id"`
	ExpectedCloseDate pgtype.Date        `json:"expected_close_date"`
	ClosedAt          pgtype.Timestamptz `json:"closed_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type Note struct {
	ID         uuid.UUID          `json:"id"`
	EntityType string             `json:"entity_type"`
	EntityID   uuid.UUID          `json:"entity_id"`
	Body       string             `json:"body"`
	AuthorID   uuid.UUID          `json:"author_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type PipelineStage struct {
	ID         uuid.UUID          `json:"id"`
	Name       string             `json:"name"`
	OrderIndex int32              `json:"order_index"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Task struct {
	ID          uuid.UUID          `json:"id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	EntityType  pgtype.Text        `json:"entity_type"`
	EntityID    uuid.NullUUID      `json:"entity_id"`
	AssigneeID  uuid.NullUUID      `json:"assignee_id"`
	DueDate     pgtype.Date        `json:"due_date"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
