// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notes.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const createNote = `-- name: CreateNote :one
INSERT INTO notes (entity_type, entity_id, body, author_id)
VALUES ($1, $2, $3, $4)
RETURNING id, entity_type, entity_id, body, author_id, created_at, updated_at
`

type CreateNoteParams struct {
	EntityType string    `json:"entity_type"`
	EntityID   uuid.UUID `json:"entity_id"`
	Body       string    `json:"body"`
	AuthorID   uuid.UUID `json:"author_id"`
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error) {
	row := q.db.QueryRow(ctx, createNote,
		arg.EntityType,
		arg.EntityID,
		arg.Body,
		arg.AuthorID,
	)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.EntityType,
		&i.EntityID,
		&i.Body,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNote = `-- name: DeleteNote :exec
DELETE FROM notes WHERE id = $1
`

func (q *Queries) DeleteNote(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteNote, id)
	return err
}

const getNote = `-- name: GetNote :one
SELECT id, entity_type, entity_id, body, author_id, created_at, updated_at
FROM notes
WHERE id = $1
`

func (q *Queries) GetNote(ctx context.Context, id uuid.UUID) (Note, error) {
	row := q.db.QueryRow(ctx, getNote, id)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.EntityType,
		&i.EntityID,
		&i.Body,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listNotesByEntity = `-- name: ListNotesByEntity :many

SELECT id, entity_type, entity_id, body, author_id, created_at, updated_at
FROM notes
WHERE entity_type = $1::text
  AND entity_id   = $2::uuid
ORDER BY created_at DESC, id DESC
LIMIT $3::int
`

type ListNotesByEntityParams struct {
	EntityType string    `json:"entity_type"`
	EntityID   uuid.UUID `json:"entity_id"`
	PageLimit  int32     `json:"page_limit"`
}

// notes.sql — workspace-scoped user-authored notes on entities.
//
// Run with search_path = workspace_<uuid>. Authoring is enforced at
// the handler layer (only the author may UPDATE; author or admin may
// DELETE — admin check sits in HTTP middleware, Sprint 7).
func (q *Queries) ListNotesByEntity(ctx context.Context, arg ListNotesByEntityParams) ([]Note, error) {
	rows, err := q.db.Query(ctx, listNotesByEntity, arg.EntityType, arg.EntityID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Note{}
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.EntityID,
			&i.Body,
			&i.AuthorID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNote = `-- name: UpdateNote :one
UPDATE notes
SET body       = $1::text,
    updated_at = now()
WHERE id = $2::uuid
RETURNING id, entity_type, entity_id, body, author_id, created_at, updated_at
`

type UpdateNoteParams struct {
	Body string    `json:"body"`
	ID   uuid.UUID `json:"id"`
}

func (q *Queries) UpdateNote(ctx context.Context, arg UpdateNoteParams) (Note, error) {
	row := q.db.QueryRow(ctx, updateNote, arg.Body, arg.ID)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.EntityType,
		&i.EntityID,
		&i.Body,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
