// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pipeline_stages.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const getPipelineStage = `-- name: GetPipelineStage :one
SELECT id, name, order_index, created_at
FROM pipeline_stages
WHERE id = $1
`

func (q *Queries) GetPipelineStage(ctx context.Context, id uuid.UUID) (PipelineStage, error) {
	row := q.db.QueryRow(ctx, getPipelineStage, id)
	var i PipelineStage
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OrderIndex,
		&i.CreatedAt,
	)
	return i, err
}

const listPipelineStages = `-- name: ListPipelineStages :many

SELECT id, name, order_index, created_at
FROM pipeline_stages
ORDER BY order_index ASC, name ASC
`

// pipeline_stages.sql — read queries for workspace pipeline stages.
//
// Queries run with search_path = workspace_<uuid>, so table names are unqualified.
// Stage writes are owned by the provisioner; v0 only exposes reads.
// UpdateDealStage lives in deals.sql.
func (q *Queries) ListPipelineStages(ctx context.Context) ([]PipelineStage, error) {
	rows, err := q.db.Query(ctx, listPipelineStages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PipelineStage{}
	for rows.Next() {
		var i PipelineStage
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OrderIndex,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
