// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: service_tokens.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createServiceToken = `-- name: CreateServiceToken :one
INSERT INTO core.service_tokens (workspace_id, name, token_hash, actor_type, scopes, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, workspace_id, name, actor_type, scopes, expires_at, last_used_at, created_at
`

type CreateServiceTokenParams struct {
	WorkspaceID uuid.UUID          `json:"workspace_id"`
	Name        string             `json:"name"`
	TokenHash   string             `json:"token_hash"`
	ActorType   string             `json:"actor_type"`
	Scopes      []byte             `json:"scopes"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

type CreateServiceTokenRow struct {
	ID          uuid.UUID          `json:"id"`
	WorkspaceID uuid.UUID          `json:"workspace_id"`
	Name        string             `json:"name"`
	ActorType   string             `json:"actor_type"`
	Scopes      []byte             `json:"scopes"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt  pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateServiceToken(ctx context.Context, arg CreateServiceTokenParams) (CreateServiceTokenRow, error) {
	row := q.db.QueryRow(ctx, createServiceToken,
		arg.WorkspaceID,
		arg.Name,
		arg.TokenHash,
		arg.ActorType,
		arg.Scopes,
		arg.ExpiresAt,
	)
	var i CreateServiceTokenRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.ActorType,
		&i.Scopes,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteServiceToken = `-- name: DeleteServiceToken :execrows
DELETE FROM core.service_tokens
WHERE workspace_id = $1 AND id = $2
`

type DeleteServiceTokenParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	ID          uuid.UUID `json:"id"`
}

func (q *Queries) DeleteServiceToken(ctx context.Context, arg DeleteServiceTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteServiceToken, arg.WorkspaceID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listServiceTokenCandidatesForVerify = `-- name: ListServiceTokenCandidatesForVerify :many
SELECT id, workspace_id, name, token_hash, actor_type, scopes, expires_at
FROM core.service_tokens
WHERE workspace_id = $1
  AND (expires_at IS NULL OR expires_at > now())
`

type ListServiceTokenCandidatesForVerifyRow struct {
	ID          uuid.UUID          `json:"id"`
	WorkspaceID uuid.UUID          `json:"workspace_id"`
	Name        string             `json:"name"`
	TokenHash   string             `json:"token_hash"`
	ActorType   string             `json:"actor_type"`
	Scopes      []byte             `json:"scopes"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

// Returns all active (non-expired) tokens for a workspace, including
// the argon2id hash so the application layer can verify a candidate
// plaintext against each row. Per-workspace token counts are small
// (dozens) so the linear verify is acceptable.
func (q *Queries) ListServiceTokenCandidatesForVerify(ctx context.Context, workspaceID uuid.UUID) ([]ListServiceTokenCandidatesForVerifyRow, error) {
	rows, err := q.db.Query(ctx, listServiceTokenCandidatesForVerify, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListServiceTokenCandidatesForVerifyRow{}
	for rows.Next() {
		var i ListServiceTokenCandidatesForVerifyRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.TokenHash,
			&i.ActorType,
			&i.Scopes,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServiceTokensByWorkspace = `-- name: ListServiceTokensByWorkspace :many

SELECT id, workspace_id, name, actor_type, scopes, expires_at, last_used_at, created_at
FROM core.service_tokens
WHERE workspace_id = $1
ORDER BY created_at DESC
`

type ListServiceTokensByWorkspaceRow struct {
	ID          uuid.UUID          `json:"id"`
	WorkspaceID uuid.UUID          `json:"workspace_id"`
	Name        string             `json:"name"`
	ActorType   string             `json:"actor_type"`
	Scopes      []byte             `json:"scopes"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt  pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

// service_tokens.sql — workspace-scoped Bearer service tokens
// (ADR-009 §4.1, Sprint 7 tasket 20260525-1006).
//
// The table lives in `core` (not the workspace schema) so a single
// application connection can authenticate Bearer requests before the
// per-workspace search_path is set. Every row carries workspace_id and
// the application is responsible for scoping reads.
func (q *Queries) ListServiceTokensByWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]ListServiceTokensByWorkspaceRow, error) {
	rows, err := q.db.Query(ctx, listServiceTokensByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListServiceTokensByWorkspaceRow{}
	for rows.Next() {
		var i ListServiceTokensByWorkspaceRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.ActorType,
			&i.Scopes,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchServiceTokenLastUsed = `-- name: TouchServiceTokenLastUsed :exec
UPDATE core.service_tokens
SET last_used_at = now()
WHERE id = $1
`

func (q *Queries) TouchServiceTokenLastUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchServiceTokenLastUsed, id)
	return err
}
