// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (title, description, entity_type, entity_id, assignee_id, due_date)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, title, description, entity_type, entity_id, assignee_id,
          due_date, completed_at, created_at, updated_at
`

type CreateTaskParams struct {
	Title       string        `json:"title"`
	Description pgtype.Text   `json:"description"`
	EntityType  pgtype.Text   `json:"entity_type"`
	EntityID    uuid.NullUUID `json:"entity_id"`
	AssigneeID  uuid.NullUUID `json:"assignee_id"`
	DueDate     pgtype.Date   `json:"due_date"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.Title,
		arg.Description,
		arg.EntityType,
		arg.EntityID,
		arg.AssigneeID,
		arg.DueDate,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.EntityType,
		&i.EntityID,
		&i.AssigneeID,
		&i.DueDate,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks WHERE id = $1
`

func (q *Queries) DeleteTask(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTask, id)
	return err
}

const getTask = `-- name: GetTask :one
SELECT id, title, description, entity_type, entity_id, assignee_id,
       due_date, completed_at, created_at, updated_at
FROM tasks
WHERE id = $1
`

func (q *Queries) GetTask(ctx context.Context, id uuid.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.EntityType,
		&i.EntityID,
		&i.AssigneeID,
		&i.DueDate,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTasksByAssignee = `-- name: ListTasksByAssignee :many

SELECT id, title, description, entity_type, entity_id, assignee_id,
       due_date, completed_at, created_at, updated_at
FROM tasks
WHERE
  ($1::uuid IS NULL
    OR assignee_id = $1::uuid)
  AND ($2::text = ''
    OR (entity_type = $2::text
        AND entity_id = $3::uuid))
ORDER BY
  completed_at NULLS FIRST,
  due_date NULLS LAST,
  created_at DESC
LIMIT $4::int
`

type ListTasksByAssigneeParams struct {
	AssigneeID uuid.NullUUID `json:"assignee_id"`
	EntityType string        `json:"entity_type"`
	EntityID   uuid.NullUUID `json:"entity_id"`
	PageLimit  int32         `json:"page_limit"`
}

// tasks.sql — workspace-scoped task list with due dates.
//
// Run with search_path = workspace_<uuid>. Reminder scheduling happens
// via River when due_date is set (apps/api/internal/jobs/task_reminder.go).
func (q *Queries) ListTasksByAssignee(ctx context.Context, arg ListTasksByAssigneeParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasksByAssignee,
		arg.AssigneeID,
		arg.EntityType,
		arg.EntityID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.EntityType,
			&i.EntityID,
			&i.AssigneeID,
			&i.DueDate,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleTaskCompletion = `-- name: ToggleTaskCompletion :one
UPDATE tasks
SET completed_at = CASE WHEN completed_at IS NULL THEN now() ELSE NULL END,
    updated_at   = now()
WHERE id = $1
RETURNING id, title, description, entity_type, entity_id, assignee_id,
          due_date, completed_at, created_at, updated_at
`

func (q *Queries) ToggleTaskCompletion(ctx context.Context, id uuid.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, toggleTaskCompletion, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.EntityType,
		&i.EntityID,
		&i.AssigneeID,
		&i.DueDate,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET title       = $1::text,
    description = $2,
    entity_type = $3,
    entity_id   = $4,
    assignee_id = $5,
    due_date    = $6,
    updated_at  = now()
WHERE id = $7::uuid
RETURNING id, title, description, entity_type, entity_id, assignee_id,
          due_date, completed_at, created_at, updated_at
`

type UpdateTaskParams struct {
	Title       string        `json:"title"`
	Description pgtype.Text   `json:"description"`
	EntityType  pgtype.Text   `json:"entity_type"`
	EntityID    uuid.NullUUID `json:"entity_id"`
	AssigneeID  uuid.NullUUID `json:"assignee_id"`
	DueDate     pgtype.Date   `json:"due_date"`
	ID          uuid.UUID     `json:"id"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.Title,
		arg.Description,
		arg.EntityType,
		arg.EntityID,
		arg.AssigneeID,
		arg.DueDate,
		arg.ID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.EntityType,
		&i.EntityID,
		&i.AssigneeID,
		&i.DueDate,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
