// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const getUserByIssuerSub = `-- name: GetUserByIssuerSub :one

SELECT id
FROM core.users
WHERE issuer = $1 AND subject = $2
`

type GetUserByIssuerSubParams struct {
	Issuer  string `json:"issuer"`
	Subject string `json:"subject"`
}

// users.sql — typed queries for the (issuer, subject) identity registry.
//
// Users are keyed on (issuer, subject) per ADR-009 §7.1; the tuple keeps
// the v0→v1 IDP migration a mapping table, not a destructive rewrite.
// Authentik issues UUID-format `subject`; Zitadel issues numeric strings.
// Returns the user_id for the given (issuer, subject) tuple, or an error
// when no matching row exists. Callers check for pgx.ErrNoRows to
// distinguish "unknown identity" from other failures.
func (q *Queries) GetUserByIssuerSub(ctx context.Context, arg GetUserByIssuerSubParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getUserByIssuerSub, arg.Issuer, arg.Subject)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertUserIdentity = `-- name: UpsertUserIdentity :one
INSERT INTO core.users (issuer, subject, email, display_name, last_login_at)
VALUES ($1, $2, NULLIF($3, ''), NULLIF($4, ''), now())
ON CONFLICT (issuer, subject) DO UPDATE SET
    email         = COALESCE(NULLIF(EXCLUDED.email, ''), core.users.email),
    display_name  = COALESCE(NULLIF(EXCLUDED.display_name, ''), core.users.display_name),
    last_login_at = now(),
    updated_at    = now()
RETURNING id
`

type UpsertUserIdentityParams struct {
	Issuer  string      `json:"issuer"`
	Subject string      `json:"subject"`
	Column3 interface{} `json:"column_3"`
	Column4 interface{} `json:"column_4"`
}

// Inserts a new user identity row or, on conflict, refreshes the mutable
// display columns and last_login_at. The (issuer, subject) tuple is
// immutable after creation; only email, display_name, and timestamps
// are updated. Returns the user's UUID in both paths.
func (q *Queries) UpsertUserIdentity(ctx context.Context, arg UpsertUserIdentityParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertUserIdentity,
		arg.Issuer,
		arg.Subject,
		arg.Column3,
		arg.Column4,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
