// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspaces.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getWorkspaceBySlug = `-- name: GetWorkspaceBySlug :one
SELECT id, slug, role_name, created_at, updated_at
FROM core.workspaces
WHERE slug = $1
`

func (q *Queries) GetWorkspaceBySlug(ctx context.Context, slug string) (CoreWorkspace, error) {
	row := q.db.QueryRow(ctx, getWorkspaceBySlug, slug)
	var i CoreWorkspace
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.RoleName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWorkspacesForTest = `-- name: ListWorkspacesForTest :many

SELECT id, slug, created_at
FROM core.workspaces
ORDER BY created_at ASC
LIMIT 10
`

type ListWorkspacesForTestRow struct {
	ID        uuid.UUID          `json:"id"`
	Slug      string             `json:"slug"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// workspaces.sql — typed queries against core.workspaces.
//
// ListWorkspacesForTest is the Week-2 Go-ramp checkpoint Test 1 surface
// (ADR-009 §1.1). It returns the first ten rows; production callers
// always scope by workspace_id resolved from the request subdomain and
// do NOT enumerate the table.
func (q *Queries) ListWorkspacesForTest(ctx context.Context) ([]ListWorkspacesForTestRow, error) {
	rows, err := q.db.Query(ctx, listWorkspacesForTest)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspacesForTestRow{}
	for rows.Next() {
		var i ListWorkspacesForTestRow
		if err := rows.Scan(&i.ID, &i.Slug, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
