// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspaces.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getWorkspaceBySlug = `-- name: GetWorkspaceBySlug :one
SELECT id, slug, role_name, created_at, updated_at
FROM core.workspaces
WHERE slug = $1 AND tombstoned_at IS NULL
`

type GetWorkspaceBySlugRow struct {
	ID        uuid.UUID          `json:"id"`
	Slug      string             `json:"slug"`
	RoleName  string             `json:"role_name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetWorkspaceBySlug(ctx context.Context, slug string) (GetWorkspaceBySlugRow, error) {
	row := q.db.QueryRow(ctx, getWorkspaceBySlug, slug)
	var i GetWorkspaceBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.RoleName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const isSlugAvailable = `-- name: IsSlugAvailable :one
SELECT NOT EXISTS (
  SELECT 1 FROM core.workspaces w WHERE w.slug = $1
) AND NOT EXISTS (
  SELECT 1 FROM core.reserved_slugs r WHERE r.slug = $1
) AS available
`

// NOTE: This check is advisory — racey with concurrent INSERT. The partial
// unique index idx_workspaces_slug_active is the authoritative constraint.
// Callers MUST handle the unique-violation error from INSERT as "slug taken".
func (q *Queries) IsSlugAvailable(ctx context.Context, slug string) (pgtype.Bool, error) {
	row := q.db.QueryRow(ctx, isSlugAvailable, slug)
	var available pgtype.Bool
	err := row.Scan(&available)
	return available, err
}

const isSlugReserved = `-- name: IsSlugReserved :one
SELECT EXISTS (
  SELECT 1 FROM core.reserved_slugs WHERE slug = $1
) AS reserved
`

func (q *Queries) IsSlugReserved(ctx context.Context, slug string) (bool, error) {
	row := q.db.QueryRow(ctx, isSlugReserved, slug)
	var reserved bool
	err := row.Scan(&reserved)
	return reserved, err
}

const listWorkspacesForTest = `-- name: ListWorkspacesForTest :many

SELECT id, slug, created_at
FROM core.workspaces
ORDER BY created_at ASC
LIMIT 10
`

type ListWorkspacesForTestRow struct {
	ID        uuid.UUID          `json:"id"`
	Slug      string             `json:"slug"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// workspaces.sql — typed queries against core.workspaces.
//
// ListWorkspacesForTest is the Week-2 Go-ramp checkpoint Test 1 surface
// (ADR-009 §1.1). It returns the first ten rows; production callers
// always scope by workspace_id resolved from the request subdomain and
// do NOT enumerate the table.
func (q *Queries) ListWorkspacesForTest(ctx context.Context) ([]ListWorkspacesForTestRow, error) {
	rows, err := q.db.Query(ctx, listWorkspacesForTest)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspacesForTestRow{}
	for rows.Next() {
		var i ListWorkspacesForTestRow
		if err := rows.Scan(&i.ID, &i.Slug, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tombstoneWorkspace = `-- name: TombstoneWorkspace :exec
UPDATE core.workspaces
SET tombstoned_at = now(), updated_at = now()
WHERE slug = $1 AND tombstoned_at IS NULL
`

func (q *Queries) TombstoneWorkspace(ctx context.Context, slug string) error {
	_, err := q.db.Exec(ctx, tombstoneWorkspace, slug)
	return err
}
